import React from 'react'
import {
  Pin20Regular,
  Pin20Filled,
  AlertOn20Regular,
  GridKanban20Regular,
  Settings20Regular,
  ArrowExit20Regular,
  Database20Regular,
  ArrowUndo20Regular,
  ArrowRedo20Regular,
  Clock20Regular,
  ChevronLeft20Regular,
  ChevronRight20Regular,
  Play20Regular,
  Pause20Regular,
  ArrowReset20Regular,
  History20Regular,
  Checkmark20Regular,
  ArrowSync20Regular,
  Dismiss20Regular,
  WeatherSunny20Regular,
  Toolbox20Regular,
  Grid20Regular,
  Edit20Regular,
  Whiteboard20Regular,
  Video20Regular,
  Info20Regular,
  Add20Regular,
  Camera20Regular,
  ChevronLeft24Regular,
  ChevronRight24Regular,
  Delete20Regular,
  Pen20Regular,
  Eraser20Regular,
  Cursor20Regular,
  Checkmark12Regular,
  ArrowLeft20Regular,
  ArrowDownload20Regular,
  Note20Regular,
  SlideMultiple20Regular,
  ArrowSort20Regular,
  ScanType20Regular,
  ArrowMaximize20Regular,
  ArrowMinimize20Regular,
  FullScreenMaximize20Regular,
  FullScreenMinimize20Regular,
  SlideText20Regular,
  TextBulletList20Regular,
} from '@fluentui/react-icons'

const iconMap: Record<string, React.ComponentType<{ className?: string; style?: React.CSSProperties }>> = {
  Pin: Pin20Regular,
  PinFilled: Pin20Filled,
  Events: AlertOn20Regular,
  FeaturePanel: GridKanban20Regular,
  Settings: Settings20Regular,
  Quit: ArrowExit20Regular,
  Database: Database20Regular,
  Undo: ArrowUndo20Regular,
  Redo: ArrowRedo20Regular,
  Clock: Clock20Regular,
  ChevronLeft: ChevronLeft20Regular,
  ChevronRight: ChevronRight20Regular,
  Play: Play20Regular,
  Pause: Pause20Regular,
  Reset: ArrowReset20Regular,
  History: History20Regular,
  Check: Checkmark20Regular,
  Restart: ArrowSync20Regular,
  Dismiss: Dismiss20Regular,
  Appearance: WeatherSunny20Regular,
  Toolbar: Toolbox20Regular,
  FeaturePanelTab: Grid20Regular,
  Annotation: Edit20Regular,
  WhiteboardTab: Whiteboard20Regular,
  VideoShow: Video20Regular,
  Info: Info20Regular,
  Add: Add20Regular,
  Capture: Camera20Regular,
  PrevPage: ChevronLeft24Regular,
  NextPage: ChevronRight24Regular,
  Delete: Delete20Regular,
  Pen: Pen20Regular,
  Eraser: Eraser20Regular,
  Cursor: Cursor20Regular,
  CheckSmall: Checkmark12Regular,
  Back: ArrowLeft20Regular,
  Download: ArrowDownload20Regular,
  Notebook: Note20Regular,
  SlideMultiple: SlideMultiple20Regular,
  Sort: ArrowSort20Regular,
  ScanType: ScanType20Regular,
  Maximize: ArrowMaximize20Regular,
  Minimize: ArrowMinimize20Regular,
  FullMaximize: FullScreenMaximize20Regular,
  FullMinimize: FullScreenMinimize20Regular,
  SlideText: SlideText20Regular,
  BulletList: TextBulletList20Regular,
}

export type IconName = keyof typeof iconMap

export interface IconProps {
  name: IconName
  className?: string
  size?: number
}

export const Icon: React.FC<IconProps> = ({ name, className, size }) => {
  const Comp = iconMap[name]
  if (!Comp) return null
  return <Comp className={className} style={size ? { fontSize: size } : undefined} />
}

export {
  Pin20Regular as PinIcon,
  Pin20Filled as PinFilledIcon,
  AlertOn20Regular as EventsIcon,
  GridKanban20Regular as FeaturePanelIcon,
  Settings20Regular as SettingsIcon,
  ArrowExit20Regular as QuitIcon,
  Database20Regular as DatabaseIcon,
  ArrowUndo20Regular as UndoIcon,
  ArrowRedo20Regular as RedoIcon,
  Clock20Regular as ClockIcon,
  ChevronLeft20Regular as ChevronLeftIcon,
  ChevronRight20Regular as ChevronRightIcon,
  Play20Regular as PlayIcon,
  Pause20Regular as PauseIcon,
  ArrowReset20Regular as ResetIcon,
  History20Regular as HistoryIcon,
  Checkmark20Regular as CheckIcon,
  ArrowSync20Regular as RestartIcon,
  Dismiss20Regular as DismissIcon,
  WeatherSunny20Regular as AppearanceIcon,
  Toolbox20Regular as ToolbarTabIcon,
  Grid20Regular as FeaturePanelTabIcon,
  Edit20Regular as AnnotationIcon,
  Whiteboard20Regular as WhiteboardTabIcon,
  Video20Regular as VideoShowIcon,
  Info20Regular as InfoIcon,
  Add20Regular as AddIcon,
  Camera20Regular as CaptureIcon,
  ChevronLeft24Regular as PrevPageIcon,
  ChevronRight24Regular as NextPageIcon,
  Delete20Regular as TrashIcon,
  Pen20Regular as PenIcon,
  Eraser20Regular as EraserIcon,
  Cursor20Regular as CursorIcon,
  Checkmark12Regular as CheckSmallIcon,
  ArrowLeft20Regular as BackIcon,
  ArrowDownload20Regular as DownloadIcon,
  Note20Regular as NotebookIcon,
  SlideMultiple20Regular as SlideMultipleIcon,
  ArrowSort20Regular as SortIcon,
  ScanType20Regular as ScanTypeIcon,
  ArrowMaximize20Regular as MaximizeIcon,
  ArrowMinimize20Regular as MinimizeIcon,
  FullScreenMaximize20Regular as FullMaximizeIcon,
  FullScreenMinimize20Regular as FullMinimizeIcon,
  SlideText20Regular as SlideTextIcon,
  TextBulletList20Regular as BulletListIcon,
}
